config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users
  resources :sections do
    collection do
      get 'search'
    end

  end
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :professors do

  collection do
    get 'search'
  end
  end

  root to: "professors#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :professor
  belongs_to :course
  has_and_belongs_to_many :students
  validates :section_number, presence: true
  validates :class_location, length: {minimum: 3}
  validates :professor_id, presence: true
  validates :course_id, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    @professors = Professor.all
    @courses = Course.all
    @students = Student.all
  end

  # GET /sections/1/edit
  def edit
    @professors = Professor.all
    @courses = Course.all
    @students = Student.all
  end

  # POST /sections
  # POST /sections.json
  def create
    @professors = Professor.all
    @courses = Course.all
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def search
    @sections = Section.where("section_number like ?", "%#{params[:q]}%")
    render :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:section_number, :class_location, :professor_id, :course_id, :students_id =>[])
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :section_number %>
    <%= form.number_field :section_number, id: :section_section_number %>
  </div>

  <div class="field">
    <%= form.label :class_location %>
    <%= form.text_field :class_location, id: :section_class_location %>
  </div>

  <div class="field">
    <%= form.label :professor_id %><br>
    <%= form.collection_select(:professor_id, @professors,:id, :first_name, include_blank: true) %>
    <br>
  </div>
    <div class="field">
      <%= form.label :course_id %><br>
      <%= form.collection_select(:course_id, @courses, :id, :course_name, include_blank: true) %>
      <br>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>
<%= form_tag(search_sections_url, method: "get") do %>
    <%= label_tag(:q,"Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Section number</th>
      <th>Class location</th>
      <th>Professor</th>
      <th>course name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.section_number %></td>
        <td><%= section.class_location %></td>
        <td><%= section.professor.last_name %></td>
        <td><%= section.course.course_name %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

</table>


<br>

<%= button_to 'New Section', new_section_path,:method=> "get" %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Section number:</strong>
  <%= @section.section_number %>
</p>

<p>
  <strong>Class location:</strong>
  <%= @section.class_location %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @section.professor.first_name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course.course_name %>
</p>
<table class="table">
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Credits</th>
    <th>Student class</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @section.students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.credits %></td>
        <td><%= student.student_class %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>




<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>