config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users
  resources :sections do
    collection do
      get 'search'
    end

  end
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :professors do

  collection do
    get 'search'
  end
  end

  root to: "professors#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :sections
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true
  validates :office_location, presence:true
  validates_format_of :email, :with => Devise::email_regexp
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def search
    @professors = Professor.where("first_name like ?", "%#{params[:q]}%")
    render :index
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:first_name, :last_name, :email, :office_location)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :professor_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :professor_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :professor_email %>
  </div>

  <div class="field">
    <%= form.label :office_location %>
    <%= form.text_field :office_location, id: :professor_office_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>
<%= form_tag(search_professors_url, method: "get") do %>
    <%= label_tag(:q,"Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
    <% end %>


<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Office location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.first_name %></td>
        <td><%= professor.last_name %></td>
        <td><%= professor.email %></td>
        <td><%= professor.office_location %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>
<%= button_to 'New Professor', new_professor_path, :method => "get" %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @professor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @professor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @professor.email %>
</p>

<p>
  <strong>Office location:</strong>
  <%= @professor.office_location %>
</p>


<p>
  <strong>Sections:</strong>
<table class="table">
  <thead>
  <tr>
    <th>Section number</th>
    <th>Location</th>
    <th>Professor</th>
    <th>Course Name</th>
    <th>Students</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @professor.sections.each do |section| %>
      <tr>
        <td><%= section.section_number %></td>
        <td><%= section.class_location %></td>
        <td><%= section.professor.last_name %></td>
        <td><%= section.course.course_name %></td>
        <td><%= link_to "list", section %> </td>
        <td><%=link_to 'Show', section %></td>
        <td><%=link_to 'Edit', edit_section_path(section) %></td>
        <td><%=link_to 'Destroy', section, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>

  <% end %>
  </tbody>
</table>
</p>





<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>